services:
  allhands22:
    image: "${TESTING_IMAGE}"

  httpenv:
    image: "${TESTING_IMAGE}"
    ports:
      - 8888:8888

    depends_on:
      - allhands22

  sut:
    image: "${TESTING_IMAGE}"
    depends_on:
      - httpenv
      - allhands22 
    ports:
      - 8888:8888

    command: curl --fail http://sut:8888 || exit 1
