services:
  allhands22:
    image: "$(TESTING_IMAGE)"

  httpenv:
    image: "$(TESTING_IMAGE)"

    depends_on:
      allhands22: 
        condition: service_started

      command: curl --fail http://localhost:8888 || exit 1
